### ISSUE TITLE
Add support for schema evolution

### ISSUE THREAD

**Issue by kdallmeyer-sr** [sksamuel/avro4k#9]
Does avro4k support reading the default value and putting it into the Avro schema? Found an issue doing an experiment with schema evolution where newer version couldn't read older version
Version "0.1.0"

```kotlin
@Serializable
data class WebhookData(val firstName: String, val lastName: String, val age: Int? = null)
```

```json
{
  "type" : "record",
  "name" : "WebhookData",
  "namespace" : "com.shoprunner.data.webhook.model",
  "fields" : [ {
    "name" : "firstName",
    "type" : "string"
  }, {
    "name" : "lastName",
    "type" : "string"
  }, {
    "name" : "age",
    "type" : [ "null", "int" ]
  } ]
}
```

Version "0.2.0"

```kotlin
@Serializable
data class WebhookData(val firstName: String, val lastName: String, val age: Int? = null, val favoriteColor: String? = null)
```

```json
{
  "type" : "record",
  "name" : "WebhookData",
  "namespace" : "com.shoprunner.data.webhook.model",
  "fields" : [ {
    "name" : "firstName",
    "type" : "string"
  }, {
    "name" : "lastName",
    "type" : "string"
  }, {
    "name" : "age",
    "type" : [ "null", "int" ]
  }, {
    "name" : "favoriteColor",
    "type" : [ "null", "string" ]
  } ]
}
```
But since default values aren't set, it can't read the older data.

**Comment by sksamuel** [comment]
There's no support for defaults at the moment.
What we could do is something similar to what we did in Avro4s and add an annotation @AvroDefault which you use to control the default values if required.

**Comment by kdallmeyer-sr** [comment]
Bummer that it's not supported. I guess the annotation is the way to go.

**Comment by kdallmeyer-sr** [comment]
I guess another option is to default the fields with types to null automatically and use the annotation to control other cases...

**Comment by kdallmeyer-sr** [comment]
For the baleen project this is how I solved using default values. Baleen uses kapt for annotation processing rather than kotlin.serializable so I'm not sure the solution is compatible. This solution was inspired by Moshii solution for deserializing json with their annotation processor.

https://github.com/ShopRunner/baleen/pull/84

**Comment by alexhwoods** [comment]
Super upvote for this feature! If I took a crack at it would you guys be willing to take a look?

**Comment by alexhwoods** [comment]
I'd go with the `@AvroDefault` approach, because getting the default values from the class isn't really plausible (Java classes don't have default fields, and so there isn't a reflection way to get them).

**Comment by alexhwoods** [comment]
Ok, I attempted this feature in [this PR](https://github.com/sksamuel/avro4k/pull/22).

It does work, and I added tests. However, let's wait for @sksamuel's feedback; it's his library.

**Comment by thake** [comment]
@kdallmeyer-sr Can you check if your use case works with version 0.22.0?

**Comment by alexhwoods** [comment]
Note that there is one limitation with the `@AvroDefault` annotation. It doesn't work for nullable fields.

Here's why:

- annotation class parameters cannot be nullable in Kotlin
- Nullable Avro fields (in this library, and often in general) only have one valid default value - null. Per the Avro spec:
```
Note that when a default value is specified for a record field whose type is a union, the type
of the default value must match the first element of the union. Thus, for unions containing
"null", the "null" is usually listed first, since the default value of such unions is typically
null.
```

And in this library nullable fields are the first type specified (i.e. `"type":["null","string"]`). That's perfectly fine, and probably should be the default behaviour.

However, unless we added a special case where we string parsed `@AvroDefault("null")`, then it can't take `null` as the default, and a string is itself invalid for `"type":["null","string"]`.

# Ideas To Add This Feature
1. String parse `"null"`, so that when the type is nullable, the default value becomes `null`.
2. Add a separate annotation, like `@AvroDefaultNull` to set null as the value.

The more I think about it, I prefer the first one.

While I really don't like squeezing everything through string types, that's a limit of annotation classes, and seems to be a community standard. If the type is nullable, then there is no other possible default value other than `null`, so it's pretty much `null` or bust at that point—so it's not like adding that special use case takes away any functionality. It's only additive.

**Comment by sksamuel** [comment]
Thorsten just added a new constant for doing this.

**Comment by alexhwoods** [comment]
That's awesome! Thanks @thake

**Comment by kdallmeyer-sr** [comment]
I'll test my use case this weekend. Thanks for looking at this!

**Comment by alexhwoods** [comment]
Here's one I'm messing around with:

```kotlin
      test("Is nullable a sufficient default value?") {
         @AvroName("Task")
         @Serializable
         data class Writer(val name: String?)

         @AvroName("Task")
         @Serializable
         data class Reader(@AvroDefault(Avro.NULL) val id: String?, val name: String?)

         val writerSchema = Avro.default.schema(Writer.serializer())
         val readerSchema = Avro.default.schema(Reader.serializer())

         val pairCompatibility = SchemaCompatibility.checkReaderWriterCompatibility(
            readerSchema,
            writerSchema
         )

         pairCompatibility.result shouldBe compatible()
      }
   }
```

It passes. If you take away the null default value, you get `READER_FIELD_MISSING_DEFAULT_VALUE`

**Comment by thake** [comment]
Closing this issue as it seems to be fixed
